### ISSUE TITLE
Better CSS for story page

### ISSUE THREAD

**Issue by TheoMadCo** [LucaPolese/LaboratorioTechWeb#4]
```css
/* 
===========
SEZIONE STORIA
===========
*/

.storyimg{
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 50%;
    height: auto;
}

.tornasu{
    display: block;
    text-align: right;
    margin-left: auto;
    max-width: fit-content;
}
```

So add class _storyimg_ and _tornasu_
